#!/bin/bash

dirname=$(dirname "$0")

hipchat_room="2068494"
hipchat_bot="github-sec"
tap_xunit="$dirname/../node_modules/.bin/tap-xunit"

mkdir ./tmp
mkdir ./artifacts
node ./ > ./tmp/log

node ./fmt < ./tmp/log \
  | ./hipchat-cli/hipchat_room_message -r "$hipchat_room" -f "$hipchat_bot"

"$tap_xunit" < ./tmp/log > ./artifacts/xunit.xml

rm -rf ./tmp
